x-logging: &x-logging
  logging:
    driver: json-file
    options:
      max-file: "5"
      max-size: "10m"

services: 
  appwrite:
    image: appwrite/appwrite:${APPWRITE_VERSION:-1.8.1}
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - mariadb
      - redis
      - openruntimes-executor
    environment:
      - _APP_ENV=${_APP_ENV}
      - _APP_OPENSSL_KEY_V1=${_APP_OPENSSL_KEY_V1}
      - _APP_DOMAIN=${_APP_DOMAIN}
      - _APP_DOMAIN_TARGET=${_APP_DOMAIN_TARGET}
      - _APP_DOMAIN_FUNCTIONS=${_APP_DOMAIN_FUNCTIONS}
      - _APP_DB_HOST=${_APP_DB_HOST}
      - _APP_DB_PORT=${_APP_DB_PORT}
      - _APP_DB_SCHEMA=${_APP_DB_SCHEMA}
      - _APP_DB_USER=${_APP_DB_SCHEMA}
      - _APP_DB_PASS=${_APP_DB_PASS}
      - _APP_DB_ROOT_PASS=${_APP_DB_ROOT_PASS}
      - _APP_REDIS_HOST=${_APP_REDIS_HOST}
      - _APP_REDIS_PORT=${_APP_REDIS_PORT}
      - _APP_REDIS_PASS=${_APP_REDIS_PASS}
      - _APP_FUNCTIONS_RUNTIMES=${_APP_FUNCTIONS_RUNTIMES}
      - _APP_EXECUTOR_SECRET=${_APP_EXECUTOR_SECRET}
      - _APP_USAGE_STATS=${_APP_USAGE_STATS}
      - _APP_LOGGING_CONFIG=${_APP_LOGGING_CONFIG}

  appwrite-realtime:
    image: appwrite/appwrite:${APPWRITE_VERSION:-1.8.1}
    entrypoint: realtime
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=${_APP_ENV}
      - _APP_OPENSSL_KEY_V1=${_APP_OPENSSL_KEY_V1}
      - _APP_DB_HOST=${_APP_DB_HOST}
      - _APP_DB_PORT=${_APP_DB_PORT}
      - _APP_DB_SCHEMA=${_APP_DB_SCHEMA}
      - _APP_DB_USER=${_APP_DB_USER}
      - _APP_DB_PASS=${_APP_DB_PASS}
      - _APP_REDIS_HOST=${_APP_REDIS_HOST}
      - _APP_REDIS_PORT=${_APP_REDIS_PORT}
      - _APP_REDIS_PASS=${_APP_REDIS_PASS}
      - _APP_LOGGING_CONFIG=${_APP_LOGGING_CONFIG}
  appwrite-console:
    image: appwrite/console:7.4.7
    restart: unless-stopped
    networks:
      - appwrite

  openruntimes-executor:
    image: openruntimes/executor:0.6.11
    hostname: exc1
    <<: *x-logging
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      - appwrite
      - runtimes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-builds:/storage/builds:rw
      - appwrite-functions:/storage/functions:rw
      - /tmp:/tmp:rw
    environment:
      - OPR_EXECUTOR_ENV=${_APP_ENV}
      - OPR_EXECUTOR_SECRET=${_APP_EXECUTOR_SECRET}
      - OPR_EXECUTOR_RUNTIMES=${_APP_FUNCTIONS_RUNTIMES}
      - OPR_EXECUTOR_LOGGING_CONFIG=${_APP_LOGGING_CONFIG}

  mariadb:
    image: mariadb:10.11
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
      - MARIADB_AUTO_UPGRADE=1
    command: mysqld --innodb-flush-method=fsync

  redis:
    image: redis:7.2.4-alpine
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

networks: 
  appwrite:
    name: appwrite
  runtimes:
    name: runtimes

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-config:
